### ISSUE TITLE
License to kill?

### ISSUE THREAD

**Issue by nofxx** [weklund/Military-Rank-Web-Font-Icons#1]
What's the license for these fine set of graphics?
Was wondering if I could use on a rank/military thing app.
TY!

**Comment by weklund** [comment]
Oops sorry @nofxx on the delay.  Use away! MIT licence.

**Comment by nofxx** [comment]
Thank you @weklund !

**Comment by weklund** [comment]
No need for sourcing, but I'd love to see how you use it when it's done @nofxx ! :)

Also let me know if you need the MOSs I haven't done.

**Comment by nofxx** [comment]
Will source for sure. Thank you again.

It's an idea for an airsoft`s players hall of fame...
